name = "VTKLegacy"
uuid = "0a04e04c-3d81-46c0-89a4-d6cdbba47ab1"
authors = ["Luis Alberto Arcos Rojas"]
version = "0.0.1-DEV"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"

[compat]
CairoMakie = "0.13.1"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
